[workspace]
members = [
    "programs/*"
]
resolver = "2"

[build]
program-name = "pump_clone"

[programs.localnet]
pump_clone = "PumpC1onE11111111111111111111111111111111111"

[programs.devnet]
pump_clone = "PumpC1onE11111111111111111111111111111111111"

[programs.mainnet]
pump_clone = "PumpC1onE11111111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
url = "https://api.devnet.solana.com"
clone = [
    { address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA", filename = "spl_token-3.5.0.so" },
    { address = "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL", filename = "spl_associated-token-account-1.1.2.so" },
    { address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s", filename = "mpl_token_metadata-1.13.2.so" }
]

[[test.validator.account]]
address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
filename = "spl_token_account.json"

[[test.validator.account]]
address = "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"
filename = "spl_associated_token_account.json"

[[test.validator.account]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
filename = "mpl_token_metadata_account.json"

[features]
seeds = false
skip-lint = false
resolution = true
skip-deploy = false